services:
  web:
    image: 'mcd295/ttex'
    command: [ "python", "manage.py", "runserver", "0.0.0.0:80" ]
    volumes:
      - .:/code
    ports:
      - "80:80"
    networks:
      - app-network
  celery:
    image: 'mcd295/ttex'
    command: [ "celery", "-A", "ttex", "worker", "-l", "INFO" ]
    volumes:
      - .:/code
    networks:
      - app-network
  redis:
    image: 'redis:alpine'
    command: redis-server
    restart: always
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
