services:
  web:
    build: .
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - ttex-network
  celery:
    build: .
    command: [ "celery", "-A", "ttex", "worker", "-l", "info" ]
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - ttex-network
  db:
    image: postgres:16.2
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_NAME=
    networks:
      - ttex-network
  redis:
    image: redis:alpine
    networks:
      - ttex-network
networks:
  ttex-network:
    driver: bridge
