services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      MICROSOFT_AUTH_CLIENT_ID: /run/secrets/microsoft_auth_client_id
      MICROSOFT_AUTH_CLIENT_SECRET: /run/secrets/microsoft_auth_client_secret
      MICROSOFT_AUTH_TENANT_ID: /run/secrets/microsoft_auth_tenant_id
      MICROSOFT_AUTH_OBJECT_ID: /run/secrets/microsoft_auth_object_id
      NOTIFICATION_URL: /run/secrets/notification_url
      OAUTHLIB_RELAX_TOKEN_SCOPE: True
    secrets:
      - microsoft_auth_client_id
      - microsoft_auth_client_secret
      - microsoft_auth_tenant_id
      - microsoft_auth_object_id
      - notification_url

  celery:
    build: .
    user: "deployer"
    command: celery -A ttex worker -l INFO
    volumes:
      - .:/code
    networks:
      - app-network
    depends_on:
      - redis
    environment:
      MICROSOFT_AUTH_CLIENT_ID: /run/secrets/microsoft_auth_client_id
      MICROSOFT_AUTH_CLIENT_SECRET: /run/secrets/microsoft_auth_client_secret
      MICROSOFT_AUTH_TENANT_ID: /run/secrets/microsoft_auth_tenant_id
      MICROSOFT_AUTH_OBJECT_ID: /run/secrets/microsoft_auth_object_id
      NOTIFICATION_URL: /run/secrets/notification_url
    secrets:
      - microsoft_auth_client_id
      - microsoft_auth_client_secret
      - microsoft_auth_tenant_id
      - microsoft_auth_object_id
      - notification_url

  redis:
    image: 'redis:alpine'
    command: redis-server
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

secrets:
  microsoft_auth_client_id:
    file: ../.secrets/.microsoft_auth/microsoft_auth_client_id.txt
  microsoft_auth_client_secret:
    file: ../.secrets/.microsoft_auth/microsoft_auth_client_secret.txt
  microsoft_auth_tenant_id:
    file: ../.secrets/.microsoft_auth/microsoft_auth_tenant_id.txt
  microsoft_auth_object_id:
    file: ../.secrets/.microsoft_auth/microsoft_auth_object_id.txt
  notification_url:
    file: ../.secrets/notify/notification_url.txt
