# Generated by Django 5.0.3 on 2024-03-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='error',
        ),
        migrations.AddField(
            model_name='transcription',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
