# Generated by Django 5.0.3 on 2024-03-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_remove_transcription_error_transcription_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='title',
            field=models.CharField(default='transcription', max_length=100, unique=True),
        ),
    ]
