# Generated by Django 5.0.3 on 2024-12-18 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_transcription_uuid_alter_transcription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
