# Generated by Django 5.0.3 on 2024-12-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_alter_transcription_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
