# Generated by Django 5.0.3 on 2024-03-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_alter_transcription_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='title',
            field=models.CharField(default='transcription', max_length=100),
        ),
    ]
