# Generated by Django 5.0.3 on 2024-03-14 11:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_alter_transcription_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
