# Generated by Django 5.0.3 on 2024-12-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_transcription_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='slug',
        ),
    ]
