# Generated by Django 5.0.3 on 2024-12-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_remove_transcription_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='uuid',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
